// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHeeugAk0d9nHvrdX2dUNstYSbX3MEsk',
    appId: '1:127782893297:web:96d21d37f01d38eb585b50',
    messagingSenderId: '127782893297',
    projectId: 'finance-app-e6e1e',
    authDomain: 'finance-app-e6e1e.firebaseapp.com',
    storageBucket: 'finance-app-e6e1e.appspot.com',
    measurementId: 'G-1FWXN9TTD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRJ5Gr3o25qfjCCMkY3yiCmLJYqHQgrs',
    appId: '1:127782893297:android:29b1ab0710cd9e85585b50',
    messagingSenderId: '127782893297',
    projectId: 'finance-app-e6e1e',
    storageBucket: 'finance-app-e6e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjx9Q3yr0ACg67ADbyQagA_MJC9EM22Y0',
    appId: '1:127782893297:ios:ec92b91f23ef74cd585b50',
    messagingSenderId: '127782893297',
    projectId: 'finance-app-e6e1e',
    storageBucket: 'finance-app-e6e1e.appspot.com',
    iosClientId: '127782893297-uqgg76c1e1211jc08e2tjdg8409cogaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjx9Q3yr0ACg67ADbyQagA_MJC9EM22Y0',
    appId: '1:127782893297:ios:ec92b91f23ef74cd585b50',
    messagingSenderId: '127782893297',
    projectId: 'finance-app-e6e1e',
    storageBucket: 'finance-app-e6e1e.appspot.com',
    iosClientId: '127782893297-uqgg76c1e1211jc08e2tjdg8409cogaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenUi',
  );
}
